version: '3.3'

services:
  weatherlogger:
    build: WeatherLogger
    image: weatherlogger
    restart: always
    ports:
      - '${WEATHER_PORT:-8080}:8080'
    volumes:
      - ./data/weather:/app/data

  webapp:
    build: WebApp
    image: webapp
    volumes:
      - ./data/webapp:/app/dist
