version: '3.3'

services:
  weather-db:
    image: postgres:alpine
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - weather-network
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/ssl/server.crt:/var/lib/postgresql/server.crt
      - ./data/ssl/server.key:/var/lib/postgresql/server.key

  weather-admin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - weather-network
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PDADMIN_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  weather-network:
    driver: bridge
