version: '3.8'

services:
  weather-db:
    image: postgres:13.2-alpine
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - weather-network
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-mikudb}'
      - 'POSTGRES_USER=${POSTGRES_USER:-miku}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hatsune}'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/ssl/server.crt:/var/lib/postgresql/server.crt
      - ./data/ssl/server.key:/var/lib/postgresql/server.key

  weather-admin:
    image: dpage/pgadmin4:5.1
    restart: always
    ports:
      - '${PGADMIN_PORT:-80}:80'
    networks:
      - weather-network
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PDADMIN_EMAIL:-miku@hatsune.dev}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-hatsune}'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  weather-network:
    driver: bridge
