env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - ignoreComments: true
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: none
  no-unused-vars:
    - warn
    - vars: all
      args: none
      ignoreRestSiblings: false
      caughtErrors: none
  semi:
    - error
    - never
  max-len:
    - error
    - code: 80
  eol-last:
    - error
    - always
  keyword-spacing:
    - error
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-before-blocks:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  object-curly-newline:
    - error
    - ImportDeclaration:
        multiline: true
        minProperties: 3
      ExportDeclaration:
        multiline: true
        minProperties: 3
  comma-spacing:
    - error
    - before: false
      after: true
  spaced-comment:
    - error
    - always
    - exceptions:
        - '-'
        - '+'
      block:
        balanced: true
  no-trailing-spaces:
    - error
  no-warning-comments:
    - warn
    - terms:
        - TODO
        - FIXME
      location: anywhere
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
