name: build-checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, stable]

  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Test Build Java application
      - name: Setup OpenJDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Maven
        run: cd WeatherLogger && mvn clean install spring-boot:repackage

      # Test Build NodeJS application
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
      - name: Installing nodejs packages
        run: cd WebApp && npm i
      - name: Building webapp
        run: cd WebApp && npm run build
